### ISSUE TITLE
Mentioned directory format in the README is missing 'train' , 'test' and 'hold' directories, process_data.py

### ISSUE THREAD

**Issue by ice-pice** [DIUx-xView/xview2-baseline#1]
Hi guys, 
Thanks for providing this wonderful baseline code to start working on.
While I was going through the steps mentioned in the README, specifically to run `process_data.py` (https://github.com/DIUx-xView/xview2-baseline#damage-classification-training) , I had to slightly modify my directory structure as compared to the prescribed directory format few lines above in the README (https://github.com/DIUx-xView/xview2-baseline#other-methods) to insert `train` , `test` and `hold` subdirectories before.

To elaborate more, my directory structure looks like 
```
xBD
├── train
    ├── guatemala-volcano
    ├── hurricane-florence
    ├── hurricane-harvey
    ├── hurricane-matthew
     ...
├── test
├── hold
└── spacenet_gt
    ├── dataSet
    ├── images
    └── labels
```
Can you please look into this or correct me if I am wrong. Thanks again!

**Comment by ssajeev** [comment]
Thank you for pointing this out! This will be added to the README but `process_data.py` assumes you have an output directory with three empty subfolders for `train`, `test`, and `hold` when extracting the polygons. However, since the challenge provides you with separate train and test downloads, you can modify the script for lines 165 - 175. from what is below to the second code snippet. Then you can run it on the train and test dataset directories independently and structure the directories like https://github.com/DIUx-xView/xview2-baseline#other-methods

Before Modification
```
    logging.info("Started Processing for Train Data")
    process_data(args.input_dir, args.output_dir, 'train')
    logging.info("Finished Processing Train Data")

    logging.info("Started Processing Test Data")
    process_data(args.input_dir, args.output_dir, 'test')
    logging.info("Finished Processing Test Data")

    logging.info("Started Processing Holdout Data")
    process_data(args.input_dir, args.output_dir, 'hold')
    logging.info("Finished Processing Holdout Data")

```

After Modification
```
    logging.info("Started Processing for Data")
    process_data(args.input_dir, args.output_dir, '')
    logging.info("Finished Processing Train Data")
```

**Comment by ice-pice** [comment]
Thanks for replying @ssajeev .
I understand output folder will have `train`, `test` and `hold` dirs. My doubt was regarding the input directory. I suppose your modification will solve the issue above.

However this creates a subsequent issue. Addressing it here:
After finishing the `process_data.py` step, next step is to run `damage_classification.py` script that also takes `--test_data` and `--test_csv` as input. Looking at the script, this set has to be the validation set.
Now to obtain this validation set, I feel `process_data.py` needs changes to rng output `train.csv` and `test.csv` for the same input `train` directory.

Hopefully I made myself clear.

**Comment by ssajeev** [comment]
For now, we recommend splitting the train data beforehand rather than doing it in `process_data.py`.  We will provide an updated `process_data.py` script that will split the data in train into train and validation. We will update the README to reflect this.

**Comment by ice-pice** [comment]
Great! 
I would prefer not to close the issue before it's actually addressed in the code.
Thanks again.

**Comment by ssajeev** [comment]
The code and README have been updated with new instructions for `process_data.py`.  Please verify that it works for you.

**Comment by deg4uss3r** [comment]
@ice-pice Thanks for putting in this issue. We are going to mark it resolved. If you see any other problems please open a new issue, thanks again!

**Comment by successhaha** [comment]
Hello, where did you get the label in the test dataset? The test data set I downloaded has no labels.
