### ISSUE TITLE
Problem with inference.sh

### ISSUE THREAD

**Issue by zhaowenyi7** [DIUx-xView/xview2-baseline#8]
I was following your README, when I ran `inference.sh` using the simple call you mentioned, like

> Sample Call:  `./utils/inference.sh -x /path/to/xView2/ -i /path/to/$DISASTER_$IMAGEID_pre_disaster.png -p /path/to/$DISASTER_$IMAGEID_post_disaster.png -l /path/to/localization_weights.h5 -c /path/to/classification_weights.hdf5 -o /path/to/output/image.png -y` 

The terminal prints `Running localization` and then finished, without continuing the script. 
I was using conda environment.  And the weights you've trained.
I wonder what's wrong with my operation.

**Comment by deg4uss3r** [comment]
@zhaowenyi7 There's a good chance you're just missing a dependency or something simple. 

We hide all output to a log file so you'll want to comment out [this line](https://github.com/DIUx-xView/xview2-baseline/blob/master/utils/inference.sh#L171) and check `/tmp/inference_log` to see any obvious failures.

**Comment by deg4uss3r** [comment]
@zhaowenyi7 Is this issue resolved?

**Comment by zhaowenyi7** [comment]
Sorry for so long time, it's solved. Thanks a lot.

**Comment by deg4uss3r** [comment]
No worries @zhaowenyi7 glad I could help!
